import './js/header-scroll';
import './js/swiper';
import './js/aos';
import './js/price-modal-markup';
import './js/modals';
import './js/smooth-scroll';
import './js/phone-mask';
import './js/form';
import './js/scroll-up';
